#!/bin/bash

# Get branch name and description
BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [[ "$BRANCH_NAME" =~ "_calendar" ]]; then
  cd "hw12_13_14_15_16_calendar"
  make lint
else
  cd $BRANCH_NAME || { echo "no dir with name $BRANCH_NAME"; exit 127; }
  golangci-lint run --fix
fi

# DO THIS ONETIME BEFORE ANY COMMIT/PUSH
# $ git config core.hooksPath .git-hooks
