apiVersion: v2
name: calendar-chart
version: 0.1.0
description: Helm chart for Calendar API, Scheduler and Sender
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 18.1.13
    repository: oci://registry-1.docker.io/bitnamicharts

  - name: rabbitmq
    version: 0.10.1
    repository: oci://registry-1.docker.io/cloudpirates
