apiVersion: v1
kind: Service
metadata:
  name: calendar-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: calendar-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
